### ISSUE TITLE
is the "openSetting" method disappear at this moment ?

### ISSUE THREAD

**Issue by bau720123** [michael79bxl/cordova-plugin-nativesettings#1]
hi @michael79bxl 
I saw your teaching page and the original fork
https://github.com/michael79bxl/cordova-plugin-nativesettings
https://github.com/selahssea/Cordova-open-native-settings

"openSetting" method disappear at this moment
and I found you use the "openGlobal" to instead the original "openSetting"
and the "openGlobal" seem can't use "settingName" at all

so...
is there any reason or ???

**Comment by michael79bxl** [comment]
openGlobal opens the global settings page (android only).
